"""Deterministic active-learning selection and stage-one handoff helpers."""

from .finalize import finalize_stage1
from .scoring import (
    CANDIDATE_POOL_COLUMNS,
    CANONICAL_TILE_COLUMNS,
    DEFAULT_SCORING_BATCH_SIZE,
    DEFAULT_SCORING_NUM_WORKERS,
    SCORING_SCHEMA_VERSION,
    ScoringDependencies,
    LoadedScoringModels,
    load_scoring_models,
    normalized_class_entropy,
    resolve_active_regression_checkpoint,
    run_active_learning_scoring,
    score_tile_manifest,
    validate_scoring_inputs,
)
from .selection import (
    SelectionArtifacts,
    SelectionConfig,
    audit_geographic_leakage,
    build_geographic_splits,
    load_candidate_table,
    run_selection,
    select_active_learning,
    select_candidates,
)
from .water import (
    MAX_SELECTABLE_WATER_FRACTION,
    UNUSABLE_REASON_EXCESSIVE_WATER,
    WATER_FILTER_STATUS_EXCESSIVE,
    WATER_FILTER_STATUS_PASS,
    WATER_FILTER_STATUS_UNKNOWN,
    compute_effective_water_fraction,
    compute_satellite_water_fraction,
    evaluate_water_status,
    is_excessive_water,
    is_water_unusable,
)

__all__ = [
    "CANDIDATE_POOL_COLUMNS",
    "CANONICAL_TILE_COLUMNS",
    "DEFAULT_SCORING_BATCH_SIZE",
    "DEFAULT_SCORING_NUM_WORKERS",
    "LoadedScoringModels",
    "MAX_SELECTABLE_WATER_FRACTION",
    "SCORING_SCHEMA_VERSION",
    "ScoringDependencies",
    "SelectionArtifacts",
    "SelectionConfig",
    "UNUSABLE_REASON_EXCESSIVE_WATER",
    "WATER_FILTER_STATUS_EXCESSIVE",
    "WATER_FILTER_STATUS_PASS",
    "WATER_FILTER_STATUS_UNKNOWN",
    "audit_geographic_leakage",
    "build_geographic_splits",
    "compute_effective_water_fraction",
    "compute_satellite_water_fraction",
    "evaluate_water_status",
    "finalize_stage1",
    "is_excessive_water",
    "is_water_unusable",
    "load_candidate_table",
    "load_scoring_models",
    "normalized_class_entropy",
    "resolve_active_regression_checkpoint",
    "run_active_learning_scoring",
    "run_selection",
    "score_tile_manifest",
    "select_active_learning",
    "select_candidates",
    "validate_scoring_inputs",
]
